### ISSUE TITLE
Upgrade TNWY-H2 Green

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [dCentralizedSystems/customer-support#1]
- mount camera underneath, using L bracket, to avoid saturation, replace camera with Pi camera v2
- change rear AmpFlow motor live axle sprockets to 30T

**Comment by SimLab** [comment]
Let's do this at my place on 9/5 around 4PM. Steaks and beer on me. Patrice will be here too. Adlai is welcome as well (just confirm so I get enough steak).

**Comment by georgechrysanthakopoulos** [comment]
@adlaifelser fyi

**Comment by georgechrysanthakopoulos** [comment]
this robot was upgraded
