### ISSUE TITLE
Change color of Text data displayed on location heat map

### ISSUE THREAD

**Issue by Brinly-DaveS** [dCentralizedSystems/customer-support#15]
Having the text be yellow and the heat map be yellow to orange to red makes it very difficult to read the yellow text as it get's washed out with the heat map data. Also, I don't know what is on top of what - text should be out front / on top. 

George, this is my first attempt to add something. Hope this is what you were looking for versus an email.

**Comment by georgechrysanthakopoulos** [comment]
Thanks Dave, good feedback. I will make the change! This Issue will stay open until the change is implemented

**Comment by georgechrysanthakopoulos** [comment]
color changed to white. I will also add a slider to control how often we display the labels, right now we display them if distance between reports is more than 30 meters.

**Comment by georgechrysanthakopoulos** [comment]
added label interval slider, marking this item complete. If not, please re open
![Screen Shot 2019-06-24 at 9 34 53 AM](https://user-images.githubusercontent.com/978440/60036176-70ce2e80-9663-11e9-9175-f0feaa29d562.png)
