### ISSUE TITLE
Unit position changes based on map scale

### ISSUE THREAD

**Issue by Brinly-DaveS** [dCentralizedSystems/customer-support#17]
![image](https://user-images.githubusercontent.com/52169579/60049529-78f69000-969c-11e9-9853-057d879dfb38.png)

![image](https://user-images.githubusercontent.com/52169579/60049618-a3e0e400-969c-11e9-86cf-10805aa09199.png)

It looks like it shifts position by 30-40 ft - based on changing the map scale at lower scale ratios.

**Comment by georgechrysanthakopoulos** [comment]
@Brinly-DaveS this is a Google maps "side view" projection error, its not on our end. I think can disable "birds eye view" in the map options to prevent it, and just have top down satellite imagery only. Let me know if that works

**Comment by georgechrysanthakopoulos** [comment]
I have disabled tilt. The current unit position will still appear as if shifting, when increasing scales, , however, the path and heat map visualization is stable across scales.
