### ISSUE TITLE
Missing data points produces partial path (connectivity?)

### ISSUE THREAD

**Issue by Brinly-DaveS** [dCentralizedSystems/customer-support#19]
I went the route in black and the unit recorded the below. Any thoughts as to why it didn't pick up the whole path? This is the unit that has WiFi locally enabled, but I was not connected to it.

![image](https://user-images.githubusercontent.com/52169579/60098913-92431f00-9724-11e9-90fd-b3c2c280c3fd.png)

The unit was left on all night - so I don't believe there was a start-up issue.

Also, what application should I open a Report with - I don't seem to be getting any data - just the parameters of the report. 

Thanks.

**Comment by georgechrysanthakopoulos** [comment]
You need to select the proper time interval, on the upper left corner UI selector. Otheriwse, data can "fall out" of the last hour interval,which is the default.

i see the whole thing (plus a minor polyline artifact, which i can fix, connecting two spots)

<img width="869" alt="Screen Shot 2019-06-25 at 8 15 43 AM" src="https://user-images.githubusercontent.com/978440/60110824-97529f00-9721-11e9-98c8-b5b46b1e7580.png">

**Comment by georgechrysanthakopoulos** [comment]
To generate a report, select again the proper time span (last 6 hours has data, i just tried it) and you will a CSV file downloaded, with comma seperated values, 2 rows in your case. Excel, Numbers, any up will open it and show the tabulated format as expected. you can change unit to feet/vs miles, in the main UI
<img width="1130" alt="Screen Shot 2019-06-25 at 8 17 33 AM" src="https://user-images.githubusercontent.com/978440/60110978-e8fb2980-9721-11e9-8715-80caadde3d0a.png">
<img width="859" alt="Screen Shot 2019-06-25 at 8 17 54 AM" src="https://user-images.githubusercontent.com/978440/60110992-ef89a100-9721-11e9-8efe-bc9112e3e526.png">

**Comment by Brinly-DaveS** [comment]
I may have not picked the proper time frame and that may have kicked out some data in the above example. I re-did some test today. 

 
![image](https://user-images.githubusercontent.com/52169579/60119965-c67f0580-974d-11e9-9c4e-b86cb5ec4553.png)

Above is for Ryobi (4cf) – 6/25 – 10:04am
   
![image](https://user-images.githubusercontent.com/52169579/60119994-d3035e00-974d-11e9-954f-9d76e352430f.png)
![image](https://user-images.githubusercontent.com/52169579/60120023-e4e50100-974d-11e9-9155-384f3edebaa8.png)

Ride-on (c72) 6/24 – 11:00am - Second is Screen shot from my phone – Activity App

What do you think is causing the drop off of data?

**Comment by georgechrysanthakopoulos** [comment]
As you mention in the next, we might have a connectivity issue. The first thing I would try is to position the bin so the LTE modem has a clear path to the sky. It current is inside the case, but you can connect a 6ft USB A -> USB A (female -> male) cable and position the modem somewhere.

i will also check to see if its our filtering causing this: we use the accelerometer to determine when you are in motion, we might be to strict.

our robots (or the highway dump trucks) do not exhibit any of these artifacts, at least not in areas with good LTE coverage.

Since you have WiFi enabled, can you connect to the bin WiFi, then go to http://192.168.8.1 and check the number of "bars" you get for LTE connection?

**Comment by georgechrysanthakopoulos** [comment]
another note: if you connect to the device itself, go to its dashboard (http://192.168.8.100:8000/dashboard/ui, set the timespan properly, do you see the full path? if you dont, maybe the device is not properly connected to battery and it browns out/ restarts

**Comment by georgechrysanthakopoulos** [comment]
another thing to check: is there a particular geographic area where this happens? last few days, when you were on the west of the building, I did not see any gaps (although its hard to tell since i dont know the "ground truth" actual path)
checking the LTE connectivity from the modem itself, where you seem to be loosing reporting will definitely help.
on my side, i will create an experiment where we shield the modem, so it gets NO LTE connectivity and verify that our batching, publish on reconnect works.

**Comment by georgechrysanthakopoulos** [comment]
I have been checking around our fleet to see if I notice other LTE gaps like you are, and no luck so far. We were beating up our robot today outside, so its super bumpy, etc and no issues.
also, see images below of one of the trucks in oregon (there 3 more) that is currently carrying alot of dirt and dumping it, so lots of variability across distances, short distances etc, its all very precise, high resolution reporting with no gaps

![Screen Shot 2019-06-25 at 5 36 16 PM](https://user-images.githubusercontent.com/978440/60142775-2a1a2a80-9770-11e9-80f0-066932439d65.png)
![Screen Shot 2019-06-25 at 5 36 29 PM](https://user-images.githubusercontent.com/978440/60142776-2a1a2a80-9770-11e9-9677-8b90bc788319.png)
![Screen Shot 2019-06-25 at 5 36 48 PM](https://user-images.githubusercontent.com/978440/60142777-2a1a2a80-9770-11e9-89b7-9a74ab55eb65.png)
![Screen Shot 2019-06-25 at 5 37 41 PM](https://user-images.githubusercontent.com/978440/60142778-2a1a2a80-9770-11e9-808e-f6e025f38726.png)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2019-06-26 at 12 00 26 AM](https://user-images.githubusercontent.com/978440/60158180-759afb80-97a5-11e9-9f44-2c8320c65978.png)
all the data is there. there must have been an issue on our indexing nodes, restarting cleared it!

**Comment by Brinly-DaveS** [comment]
Thanks for plugging away on this. Today, I took the ride-on out for another spin to see if the issue was resolved. Looks like there is still an issue with data not being displayed and (new) weird positional data – compared to my path. Sorry – I forgot to turn my phone app on. Black line is path taken (roughly – hard to draw lines with a mouse). 

![6-26 Tele Trial](https://user-images.githubusercontent.com/52169579/60182562-8aea4700-97f2-11e9-935a-4afb7cca7a8c.png)

                Enjoy Whitby Island today with your next Robot delivery.

**Comment by Brinly-DaveS** [comment]
Sorry - didn't mean to close this.

**Comment by georgechrysanthakopoulos** [comment]
I was able to reproduce the issue you see, on our trip to deliver our first B3m to whidbey island. We have a telemetry bin in my truck, and if you inspect the series of pictures below, there are missing data for 15 minutes (out of a 6 hour trip with 5 second gps reports!) between 3:35PST and 3:50PST 6/26.

https://photos.app.goo.gl/m6yhjY4aosu72uhdA

basically, at the start of our trip back, we went "dark" and did not report anything for 15 . minutes until we were back at the ferry terminal heading back. this is a 95 mile trip and nowhere else in this trip do we notice this gap: our data is very accurate and timely. still no clues why there is this "gap", given we queue and publish on LTE issues, it could be a modem issue, it could be vibration related (but i doubt it, given it is not easy to reproduce across robots, dump trucks, etc) or a SW issue (our bug).

**Comment by Brinly-DaveS** [comment]
Good that you were able to reproduce it. If I can help test to see how to resolve, don’t hesitate to ask. Our units seem to do it more than any others. 





Sent from my iPhone

On Jun 26, 2019, at 10:41 PM, George Chrysanthakopoulos <notifications@github.com> wrote:




I was able to reproduce the issue you see, on our trip to deliver our first B3m to whidbey island. We have a telemetry bin in my truck, and if you inspect the series of pictures below, there are missing data for 15 minutes (out of a 6 hour trip with 5 second
 gps reports!) between 3:35PST and 3:50PST 6/26.
https://photos.app.goo.gl/m6yhjY4aosu72uhdA
basically, at the start of our trip back, we went "dark" and did not report anything for 15 . minutes until we were back at the ferry terminal heading back. this is a 95 mile trip and nowhere else in this trip do we notice this gap: our data is very accurate
 and timely. still no clues why there is this "gap", given we queue and publish on LTE issues, it could be a modem issue, it could be vibration related (but i doubt it, given it is not easy to reproduce across robots, dump trucks, etc) or a SW issue (our bug).
—
You are receiving this because you modified the open/close state.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by georgechrysanthakopoulos** [comment]
Lets schedule a time next week, where I can talk to the person driving the unit, and we can collect some data on where it seems to loose data.

my current theory is that the modem "swallows" packets when it roams between networks, without reporting failure. it does not appear to be in our SW, or other electronics. our retry/buffering seems to work.
out of 28 units, I have only seen it on my truck, and on yours

**Comment by Brinly-DaveS** [comment]
Let’s talk on Tuesday afternoon – say 4pm Eastern.

                I’ve been driving some of the units – so I’m the person to talk to.

                I’d also like to get some training on the UI and understanding when I’m connected to the unit that has WiFi enabled – how I know I’m on the unit looking at it’s data.

                Thanks.

**Comment by georgechrysanthakopoulos** [comment]
i believe I found a SW issue causing the data loss. Might not be the only cause, but it would definately cause a set of batched packets to go missing if the upload of the previous batch took a few seconds more than it should (our code allows for several minutes of jitter in the data connection, so so this clearly was a place that we were too sensitive)

will test and confirm. in places with solid LTE coverage this bug would not manifest easily, but it could reproduce anywhere

**Comment by georgechrysanthakopoulos** [comment]
looks like data loss is considerably less given these two paths (ground truth and tele bin)
![image015](https://user-images.githubusercontent.com/978440/60527943-2b83af80-9ca8-11e9-80d7-39ff6dacdf73.jpg)
![image014](https://user-images.githubusercontent.com/978440/60527944-2c1c4600-9ca8-11e9-9227-e1c9fcaa80d2.jpg)

i will look on them with the UI to see where the gaps are

**Comment by georgechrysanthakopoulos** [comment]
![image001](https://user-images.githubusercontent.com/978440/60533973-aef7cd80-9cb5-11e9-8403-958e8e1ef0f9.png)
ground truth for images above, showing missing path sections

**Comment by georgechrysanthakopoulos** [comment]
the data appears to be there, its split across our two replicated stream processing nodes. Anticipating replication issues we already brodacast to both nodes for data, then merge, but I believe our merge, on the UI side, is squashing data in the same timeseries bin.
see these two images, from each node and notice that they have complementary data
![ec2-35-165-222-131](https://user-images.githubusercontent.com/978440/60538650-d8b5f200-9cbf-11e9-8470-f3fd596d2b59.png)
![ec2-54-189-187-82](https://user-images.githubusercontent.com/978440/60538651-d8b5f200-9cbf-11e9-9815-cb30d777c230.png)

**Comment by georgechrysanthakopoulos** [comment]
fixed! it was a javscript/ UI side bug, on the timeseries merge across multiple back end (cloud processing) nodes
![Screen Shot 2019-07-02 at 2 16 49 PM](https://user-images.githubusercontent.com/978440/60547258-0e64d600-9cd4-11e9-8268-7f7e1607eeca.png)

**Comment by georgechrysanthakopoulos** [comment]
re opening, since we still seem to be missing some batched data samples. Over the span of 4 hours, 26 minutes worth of samples (we expect about 12 samples per minute) are missing, at seemingly random intervals. it looks like edge did not send, or they goto swallowed. not UI side

ground truth, from Dave:
![image001](https://user-images.githubusercontent.com/978440/60613374-9d7af800-9d7f-11e9-8f1a-cb414db2f7fd.png)
our capture, 6 hours time span. Its pretty accurate, but UI code that detects gaps shows missing data:
![Screen Shot 2019-07-03 at 10 43 09 AM](https://user-images.githubusercontent.com/978440/60613414-b2f02200-9d7f-11e9-91a2-17bf890c01d6.png)

we can work around LTE issue by re sending data up , even if they are duplicates (the cloud will discard dupes). Before i start doing that I want us to collect more data< i was expecting more issues are lurking

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2019-07-05 at 2 05 56 PM](https://user-images.githubusercontent.com/978440/60745200-0acc8b80-9f2e-11e9-8777-183ff51959e1.png)
path from today, Dave, if you have it, please post the ground truth. From what i can tell, it looks good (if you post the ground truth I can compare, have our analysis code flag gaps)

**Comment by Brinly-DaveS** [comment]
I was off on Friday, except between 7 and 8:30 am so I’m not sure what path you are looking at.  Sorry.
