### ISSUE TITLE
sensors/visual-svm-feature-detectors/default/ui/ Reset seems not to be working

### ISSUE THREAD

**Issue by AlchemyGeek** [dCentralizedSystems/customer-support#2]
Clicking on the reset button doesn't remove from the screen the dots selected from the previous training process. Not clear of it resets and doesn't remove dots or doesn't reset. See attached image.
![custom_feature_detection_service](https://user-images.githubusercontent.com/5317747/44876735-b3e38f00-ac56-11e8-9337-438a2889ea58.png)

**Comment by georgechrysanthakopoulos** [comment]
the dots are not features, they are in progress pixel patches. if you click on the middle red dot (the original centroid) they will create an actual support vector, and clicking on state you will see it in the training sets.
there is small text, in the actual UI screen, with instructions, but I will post a video on how to use this "dev" UI soon. I will keep the issue open, until i have the video ready

**Comment by georgechrysanthakopoulos** [comment]
added wiki page with link to new video tutorial:

https://github.com/dCentralizedSystems/customer-support/wiki/SVMFeatureDetectorGuide
