### ISSUE TITLE
Display day/hour/min/secs on route markers

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [dCentralizedSystems/customer-support#23]

**Comment by georgechrysanthakopoulos** [comment]
done, note we now capture every 5 seconds, and publish once a minute

![Screen Shot 2019-06-25 at 3 55 57 PM](https://user-images.githubusercontent.com/978440/60139173-ca1c8780-9761-11e9-8555-fc16132bc249.png)

**Comment by Brinly-DaveS** [comment]
Excellent. That really helps me in troubleshooting the gaps in path that we seem to be having. Good to Close it from my standpoint.
