### ISSUE TITLE
User has to login every time they switch from individual asset view to fleet view

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [dCentralizedSystems/customer-support#27]

**Comment by adamdgreen** [comment]
Seems to be a Safari vs Chrome issue.  Same as the camera on the robot.  Using Chrome, I'm able to switch between individual assets and fleet view without having to re login.

**Comment by georgechrysanthakopoulos** [comment]
closing this, since there is a work around, will track internally as a Safari compatibility issue
