### ISSUE TITLE
Need a way to hook implements to robots

### ISSUE THREAD

**Issue by SimLab** [dCentralizedSystems/customer-support#3]
I'd love to be able to pull our John Deere cart using the robots. Here are the pictures of how it attaches to the John Deere tractor.
![20180902_154913617_ios](https://user-images.githubusercontent.com/1661796/44958103-0f4c9180-ae90-11e8-901f-eeead65ab0b9.jpg)

![attachment](https://user-images.githubusercontent.com/1661796/44958118-3a36e580-ae90-11e8-864c-61b7e5a0e4d8.JPG)

**Comment by georgechrysanthakopoulos** [comment]
We have 2x 12 Tooth sprockets to fix the loose chain, and if you plan to visit SODO soon, we will have a pulling attachment ready for you so you can just go home and bolt to the robot.
