### ISSUE TITLE
Defining Work Areas Using "Paint" Option

### ISSUE THREAD

**Issue by adamdgreen** [dCentralizedSystems/customer-support#30]
Can the "paint" option be used to define the work area boundary while manually driving the robot?  

Currently, the work area is defined by selecting a tether location and then a fixed radius or grid in the map view.  While this works well in areas with a clear map view its difficult to define boundary's that are obscured by trees, overhead objects, shadows etc.  

In the ideal scenario, the user would have 3 options to define the work area. 
 1. Manually drive the robot around the perimeter of the work area to create a goefence.  Once the goefence is created the robot would be released in full autonomous mode.
2. Define a tether location and fixed radius/grid pattern (Currently in use)
3. Use a smart phone to mark a "here" location as boundary location

The work area would be defined one time by the user and then be stored for repetitive use.

**Comment by georgechrysanthakopoulos** [comment]
this is a good suggestion, but it might take a while to implement. i ll keep this Issue open. until then, please use tethers

**Comment by georgechrysanthakopoulos** [comment]
we now support user defined work areas, and exclusion areas (obstacles), using arbitrary size rectangles. The user can drag the rectangle by clicking in center, and also change its dimensions interactively
https://photos.app.goo.gl/TXb2JF5bJt6YR5rn6
