### ISSUE TITLE
Add Undo Button to UI

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#34]
HIGH PRIORITY (Not sure how to tag this a ticket).

Really easy - especially in mobile UI - to make mistakes and change things unintentionally that take time to redo.

A redo button (that knows how to revert multiple steps) would mitigate a lot of this pain.

**Comment by georgechrysanthakopoulos** [comment]
I agree. I have created an internal Issue to track

**Comment by georgechrysanthakopoulos** [comment]
first order implementation in (edge only, cloud support next). we support multi version undo
https://photos.app.goo.gl/DtpKz2xHo8xB5e1p7
