### ISSUE TITLE
Ruler + Scale Needed in Planning UI

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#37]
1. It'd be much easier if there was a scale shown (e.g., 1" = 10 ft) show at each zoom level on the map.

2. It'd be great if we could support a smiple ruler tool (ala Google Earth) so that user could measure various lengths.

**Comment by georgechrysanthakopoulos** [comment]
there might be a UI widget on the google api that allows me to enable this, per map, good suggestion.

**Comment by georgechrysanthakopoulos** [comment]
scale control is now enabled. need to make some map <div> element height fixes so its always visible
<img width="471" alt="Screen Shot 2020-07-16 at 6 19 51 AM" src="https://user-images.githubusercontent.com/978440/87675593-6b3efd00-c72c-11ea-989d-793b525da94a.png">
