### ISSUE TITLE
Navigation Settings Values Changed Unexpectedly

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#39]
I configured my navigation settings (user turn = 0.25, obstacle avoidance=off).
I started mowing.
All good.
I then set obstacle avoidance = on
the value of user turn changed to 0.50 (not expected). I expected all my other values to remain as they were until **I** changed them.

**Comment by georgechrysanthakopoulos** [comment]
I agree. User preferences relating to sensitivity are currently ephemeral and reset on page refresh. we can persist them in the future. easy to do.

**Comment by georgechrysanthakopoulos** [comment]
created internal issue to track. it will be associated with the "default" navigation plan, under the covers, so its also replicated to the cloud
