### ISSUE TITLE
Highest Zoom Level Not Sufficient

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#43]
At the highest Zoom level in the Cloud UI, I have difficulty seeing certain characteristic of my property.

Google Earth offers a higher zoom level in which these characteristics are readily visible.

For example, resolution not sufficient to lay down an exclusion area where a long, poly-linear fence is on my property.

Can we offer better zoom?

**Comment by georgechrysanthakopoulos** [comment]
we can not, currently, through the google maps API, which is lightweight enough to render on all kinds of phones, etc. Google earth is much heavier weight, premium, etc. I will keep the issue open and we can investigate more in the future, maybe there are tiers for the google maps subscriptions that give us better zoom

**Comment by georgechrysanthakopoulos** [comment]
adding tilt now gives you higher zoom and allows you to change orientation to very accurately place markers. there is no higher zoom level, i triple checked.
<img width="573" alt="Screen Shot 2020-07-16 at 6 02 39 AM" src="https://user-images.githubusercontent.com/978440/87673823-f965b400-c729-11ea-941d-a7502a01debe.png">
<img width="720" alt="Screen Shot 2020-07-16 at 6 02 27 AM" src="https://user-images.githubusercontent.com/978440/87673843-fd91d180-c729-11ea-8a7e-797cb8787fa6.png">
<img width="826" alt="Screen Shot 2020-07-16 at 6 00 55 AM" src="https://user-images.githubusercontent.com/978440/87673849-fec2fe80-c729-11ea-90ff-98927d9a84eb.png">
<img width="640" alt="Screen Shot 2020-07-16 at 6 00 47 AM" src="https://user-images.githubusercontent.com/978440/87673850-ff5b9500-c729-11ea-9eff-7d9d646e60a5.png">
