### ISSUE TITLE
Undo Button Implementation Comments

### ISSUE THREAD

**Issue by Daadan** [dCentralizedSystems/customer-support#44]
I see “undo” arrow buttons appearing sometimes (I recognize that I am commenting on a pre-pre-release).
 
a.	They interfere a little (consider putting them on a toolbar in a fixed location in the UI rather than right next to the object just edited).
b.	I expect to be able to perform multiple, sequential Undo’s for all edits I made during my session (like Undo’s in MS Office)

**Comment by georgechrysanthakopoulos** [comment]
there is no Undo support right now, so not sure what these icons are. They must be from google maps api. Can you please add a screenshot if you see them? They are likely the map orientation/perspective icons that I can disable programmatically.

**Comment by Daadan** [comment]
I sent you a screenshot of the phantom "Undo" button via email.

**Comment by georgechrysanthakopoulos** [comment]
internal issue created, implemented first order functionality already

https://photos.app.goo.gl/DtpKz2xHo8xB5e1p7
