### ISSUE TITLE
Robot Continues to Move When Not Touching Phone

### ISSUE THREAD

**Issue by adamdgreen** [dCentralizedSystems/customer-support#7]
It's happened a couple of times and always when I'm in manual mode (holding and tilting the phone to move the robot.)  When I received a phone call, the phone switched from the Navigation Services screen to the phone call.  The robot continued to move in the same direction and speed.  Had to quickly drop the call and get back to navigation screen to stop the robot.

The robot has also moved when my phone screen switched from portrait to landscape mode.  Usually the robot stops (as seen in video) but occasionally it continues moving until I re engage the phone.  My cracked screen could also be a factor? 

[Drag.mov.zip](https://github.com/dCentralizedSystems/customer-support/files/3016311/Drag.mov.zip)

**Comment by georgechrysanthakopoulos** [comment]
ok, this is likely a bug on our side. The landscape mode is know, but I can check in code in the UI to stop the robot when this happens, force a refresh. In the meantime, lock your phone orientation so it does not switch to landscape, until I fix this.

for the video call, i can also make our UI force stop when browser is not the active application. need to think about how to do this,

**Comment by georgechrysanthakopoulos** [comment]
created internal issue to track:
https://github.com/dCentralizedSystems/cap-ui/issues/38

**Comment by georgechrysanthakopoulos** [comment]
This should now be fixed: we issue a zero velocity request when orientation changes, and we reload the page. We also zero out velocity when the browser app goes into the background. @adamdgreen please verify(somewhere safe, with lots of room for robot to roam, in case its not fixed) and post back here, at your convenience, then I can close this issue.

**Comment by georgechrysanthakopoulos** [comment]
i verified this is fixed: when you switch from your browser, we will issue a zero velocity and stop the robot. Also, when the orientation changes, we disable the navigator, and you will need to re-enable, once you have portrait orientation again. In general I will update the tutorial to say that user should lock their phone in "portrait" mode, but either way, its all much safer now
